obstacle_range: 2.5
raytrace_range: 2.0
footprint: [[-0.360, -0.25], [-0.360, 0.25], [0.360, 0.25], [0.305, -0.25]]
inflation_radius: 0.5
cost_scaling_factor: 4.0
transform_tolerance: 10
planner_frequency: 1.0
planner_paitence: 5.0

origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
