local_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 5.0 #before 12.0
  publish_frequency: 6.0 #before 2.0

  static_map: false

  lethal_cost_threshold: 100
  rolling_window: true

  width: 5
  height: 5

  resolution: 0.05 #increase to for higher res 0.025

  transform_tolerance: 0.5
  cost_scaling_factor: 4.0
  inflation_layer: {inflation_radius: 0.8, cost_scaling_factor: 3.0 }
  obstacle_layer:
    observation_sources: laser_scan_sensor
    obstacle_range: 4
    raytrace_range: 5

  planner_frequency: 2.0
  planner_paitence: 5.0

  track_unknown_space: false
  combination_method: "Maximum"

  observation_sources: scan
  scan: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: range_layer,   type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}