shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 6.0

planner_frequency: 5.0
planner_patience: 5.0

oscillation_timeout: 10 #before 10
oscillation_distance: 0.5 #before 0.2

recovery_behavior_enabled: true

# base_global_planner: NavfnROS
# base_local_planner: TrajectoryPlannerROS

# local planner - default is trajectory rollout
TrajectoryPlannerROS: "dwa_local_planner/DWAPlannerROS"
